volumes:
  myapp-mysql-data:
  myapp-mysql-test-data:
  myapp-minio:

x-common-environment: &common-environment
  AWS_ACCESS_KEY_ID: user
  AWS_SECRET_ACCESS_KEY: password
  AWS_REGION: ap-northeast-1
  AWS_S3_BUCKET: myapp-upload-develop
  AWS_URL: http://minio:9000
  DB_USER: user
  DB_PASSWORD: password
  DB_HOST: myapp-mysql

services:
  app:
    container_name: myapp-app
    build: .
    ports:
      - "3000:3000"
    environment:
      <<: *common-environment
      HOST_DOMAIN: localhost:3000
    networks:
      - myapp_network
    volumes:
      - .:/myapp
    tty: true
    stdin_open: true
    command: sh -c 'rm -rf tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0'
    depends_on:
      - mysql
      - mysql-test

  tailwindcss:
    container_name: myapp-tailwindcss
    build: .
    networks:
      - myapp_network
    volumes:
      - .:/myapp
    tty: true
    stdin_open: true
    command: bundle exec rails tailwindcss:watch

  mysql:
    image: mysql:8.0
    container_name: myapp-mysql
    ports:
      - "3306:3306"
    volumes:
      - myapp-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - myapp_network

  mysql-test:
    image: mysql:8.0
    container_name: myapp-mysql-test
    ports:
      - "13306:3306"
    volumes:
      - myapp-mysql-test-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: myapp_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - myapp_network

  minio:
    container_name: myapp-minio
    image: minio/minio
    ports:
      - '9000:9000'
      - '8900:8900'
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    volumes:
      - myapp-minio:/data/minio
    networks:
      - myapp_network
    command: 'minio server /data/minio --console-address ":8900"'

networks:
  myapp_network:
    external: true
